### ISSUE TITLE
cuda tensor

### ISSUE THREAD

**Issue by 123wk45678** [YukeWang96/DSXplore#1]
when i run mdoels/resnet.py , 我运行test（）函数，then i meet a bug
"
output = scc_cuda.forward(input, weights, output, overlap)[0]
RuntimeError: input must be a CUDA tensor
"
这个是什么原因呢？我也将全部计算放在gpu上了

**Comment by 123wk45678** [comment]
my env is python 3.8 and nvcc is 11.1

**Comment by 123wk45678** [comment]
sorry 应该是这个问题：
“
output = scc_cuda.forward(input, weights, output, overlap)[0]
RuntimeError: weights must be a CUDA tensor
”

**Comment by YukeWang96** [comment]
Hi,

I just fix the problem you mentioned in the `test()` function in `resnet.py` and now it becomes like [this](https://github.com/YukeWang96/DSXplore/blob/a53190f7c36ccd055bc91b36404d4ee6eab2b81d/models/resnet.py#L161-L163). 
I would also like to recommend to run `python main.py` as the entry point.

**Comment by YukeWang96** [comment]
> sorry 应该是这个问题：
> “
> output = scc_cuda.forward(input, weights, output, overlap)[0]
> RuntimeError: weights must be a CUDA tensor
> ”

Hi,

I just fix the problem you mentioned in the `test()` function in `resnet.py` and now it becomes https://github.com/YukeWang96/DSXplore/blob/a53190f7c36ccd055bc91b36404d4ee6eab2b81d/models/resnet.py#L161-L163

Note that both the `model` and `input` should be on GPU.
I would also like to recommend to run `python main.py` as the entry point.

**Comment by 123wk45678** [comment]
ok，thank you
